### ISSUE TITLE
Unknown module type - Lagom microservice

### ISSUE THREAD

**Issue by pk044** [playframework/play-spring-loader#15]
project link: https://github.com/ashofthephoenix/lagom-spring-di
ive been trying to replace Guice with Spring DI, but I encountered this:

https://gist.github.com/ashofthephoenix/a3bc6b1837723d9c7827d09c8eadf239

I assume the culprit is this code:

```
public class HelloModule extends Module {
  @Override
  public Seq<Binding<?>> bindings(Environment environment, Configuration configuration) {
    return seq(
            bind(HelloService.class).to(HelloServiceImpl.class)
    );
  }
}
```

I am not familiar with the Play framework(yet), does it need anything else? I looked into this:
https://www.playframework.com/documentation/2.6.x/JavaDependencyInjection#Play-libraries
Seems to be correct.
Thanks in advance!

**Comment by eximius313** [comment]
looks like simmilar issue: https://github.com/playframework/play-spring-loader/issues/14
