### ISSUE TITLE
Update documentation of Migration Guide

### ISSUE THREAD

**Issue by eximius313** [playframework/play-spring-loader#4]
If you want to migrate your app from Guice to Spring you must:
1) remove ```guice``` from your ```libraryDependencies``` in ```build.sbt``` file
2) Place ```PlaySpringDIConfiguration``` in your root package or add additional ```@ComponentScan``` annotations to it
3) Make sure to annotate all of your controllers as ```@Component``` and services as ```@Service```

If you were using JPA it's even more complicated. Besides all of the above steps you must:
1) remove ```javaJpa``` (```jpa```) from your ```libraryDependencies``` in ```build.sbt``` file
2) add ```"org.springframework" % "spring-orm" % "4.3.12.RELEASE"``` to your ```build.sbt``` file
3) you can remove from following lines from your ```application.conf```:
```
db {
  default {
          driver=X
          url="X"
          username=X
          password=X
          jndiName=DefaultDS
  }
}
```
4) you must add following lines to your persistence.xml:
```
<property name="javax.persistence.jdbc.driver" value="X" />
<property name="javax.persistence.jdbc.url" value="jdbc:X" />
<property name="javax.persistence.jdbc.user" value="X" />
<property name="javax.persistence.jdbc.password" value="X" />
```
and remove this line: ```<non-jta-data-source>DefaultDS</non-jta-data-source>```
5) you must change your ```PlaySpringDIConfiguration``` to:
```
@Configuration
@ComponentScan
@EnableTransactionManagement
public class PlaySpringDIConfiguration {

  @Bean
  public LocalEntityManagerFactoryBean entityManagerFactoryBean() {
     LocalEntityManagerFactoryBean factoryBean = new LocalEntityManagerFactoryBean();
     factoryBean.setPersistenceUnitName("defaultPersistenceUnit");
     return factoryBean;
  }

  @Bean
  public JpaTransactionManager transactionManager(EntityManagerFactory entityManagerFactory) {
     JpaTransactionManager transactionManager = new JpaTransactionManager();
     transactionManager.setEntityManagerFactory(entityManagerFactory);
     return transactionManager;
  }
}
```
6) Annotate all of your repositories as ```@Repository```
7) Replace all ```@Inject JPAApi jpaApi;``` with ```@PersistenceContext EntityManager entityManager;```
8) Replace all ```play.db.jpa.Transactional``` with ```javax.transaction.Transactional```

and it should work.

**Comment by gmethvin** [comment]
@eximius313 A pull request to update the readme would be welcome.

**Comment by gmethvin** [comment]
Also there is an example project which you can add to at `examples/spring-java`. Or you can add another example.

**Comment by landsman** [comment]
ping :thinking:

**Comment by TimMoore** [comment]
Looks like it was done in #10.
